# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 04:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spentstockitem',
            name='current_quantity',
            field=models.IntegerField(default=0, verbose_name='\u0442\u0435\u043a\u0443\u0449\u0435\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spentstockitem',
            name='quantity',
            field=models.IntegerField(verbose_name='\u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='spentstockitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockItem', validators=[django.core.validators.MinValueValidator(0)], verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
