# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 22:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0444\u0435')),
                ('timezone', models.CharField(choices=[(-1100, b'-11:00'), (-1000, b'-10:00'), (-930, b'-09:30'), (-900, b'-09:00'), (-800, b'-08:00'), (-700, b'-07:00'), (-600, b'-06:00'), (-500, b'-05:00'), (-430, b'-04:30'), (-400, b'-04:00'), (-330, b'-03:30'), (-300, b'-03:00'), (-200, b'-02:00'), (-100, b'-01:00'), (0, b'+00:00'), (100, b'+01:00'), (200, b'+02:00'), (300, b'+03:00'), (330, b'+03:30'), (400, b'+04:00'), (430, b'+04:30'), (500, b'+05:00'), (530, b'+05:30'), (545, b'+05:45'), (600, b'+06:00'), (630, b'+06:30'), (700, b'+07:00'), (800, b'+08:00'), (845, b'+08:45'), (900, b'+09:00'), (930, b'+09:30'), (1000, b'+10:00'), (1030, b'+10:30'), (1100, b'+11:00'), (1130, b'+11:30'), (1200, b'+12:00'), (1300, b'+13:00'), (1345, b'+13:45'), (1400, b'+14:00')], max_length=255, verbose_name='\u0412\u0440\u0435\u043c\u0435\u043d\u043d\u0430\u044f \u0437\u043e\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0444\u0435',
                'verbose_name_plural': '\u041a\u0430\u0444\u0435',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u0430\u0440\u0438\u0444\u0430')),
                ('default_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u043c\u0438\u043d\u0443\u0442\u0443 \u043f\u043e-\u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe', verbose_name='\u041a\u0430\u0444\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u0430\u0440\u0438\u0444',
                'verbose_name_plural': '\u0422\u0430\u0440\u0438\u0444\u044b',
            },
        ),
        migrations.CreateModel(
            name='RatePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('time_end', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u043c\u0438\u043d\u0443\u0442\u0443')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Rate', verbose_name='\u0422\u0430\u0440\u0438\u0444')),
            ],
            options={
                'verbose_name': '\u0426\u0435\u043d\u0430 \u0432 \u043f\u0435\u0440\u0438\u043e\u0434\u0435',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b \u0432 \u043f\u0435\u0440\u0438\u043e\u0434\u0435',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u043e\u043b\u0430')),
                ('active', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d?')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe', verbose_name='\u041a\u0430\u0444\u0435')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Rate', verbose_name='\u0422\u0430\u0440\u0438\u0444')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u043e\u043b\u0438\u043a',
                'verbose_name_plural': '\u0421\u0442\u043e\u043b\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e?')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435')),
                ('total_cost', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='\u0418\u0442\u043e\u0433\u043e\u0432\u0430\u044f \u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='\u0441\u0432\u043e\u0434\u043a\u0430')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Table', verbose_name='\u0421\u0442\u043e\u043b\u0438\u043a')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
    ]
